name: Render Website

on:
  push:
    branches:
      - main

jobs:
  render-slides:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file:
          - slides
          - report

    container:
      image: rocker/tidyverse:4.4.0

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          install2.r data.table slurmR
    
      - name: Render ${{ matrix.file }}
        run: |
          quarto render ${{ matrix.file }}.qmd
    
      - name: Save as artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.file }}.html
          name: ${{ matrix.file }}
